table account {
  userId varchar(255) [not null]
  type varchar(255) [not null]
  provider varchar(255) [not null]
  providerAccountId varchar(255) [not null]
  refresh_token varchar(255)
  access_token varchar(255)
  expires_at int
  token_type varchar(255)
  scope varchar(255)
  id_token text
  session_state varchar(255)

  indexes {
    (provider, providerAccountId) [pk]
    userId [name: 'userId_idx']
  }
}

table attachments {
  id serial [pk, not null, increment]
  url varchar(256) [not null]
  secret_id int
}

table friendship {
  user_id varchar(255) [not null]
  friend_id varchar(255) [not null]
  request_accepted boolean [not null, default: false]

  indexes {
    (user_id, friend_id) [pk]
  }
}

table secrets {
  id serial [pk, not null, increment]
  title varchar(256) [not null]
  shareable_url varchar(256) [not null, unique]
  content text [not null]
  revealing_date datetime [not null]
  revealed boolean
  encryption_type enum('RC4','DES','Rabbit','AES') [not null, default: 'RC4']
  edited_at datetime
  created_at datetime
  was_edited boolean [default: false]
  created_by_user_id varchar(256) [not null]

  indexes {
    revealed [name: 'revealed_idx']
    created_by_user_id [name: 'created_by_idx']
  }
}

table session {
  sessionToken varchar(255) [pk, not null]
  userId varchar(255) [not null]
  expires timestamp [not null]

  indexes {
    userId [name: 'userId_idx']
  }
}

table user {
  id varchar(255) [pk, not null]
  name varchar(255)
  username varchar(255) [unique]
  email varchar(255) [not null, unique]
  emailVerified timestamp(3) [default: `(now())`]
  image varchar(255)

  indexes {
    name [name: 'name_idx']
  }
}

table users_to_secrets {
  userId varchar(255) [not null]
  secretId int [not null]

  indexes {
    (userId, secretId) [pk]
  }
}

table verificationToken {
  identifier varchar(255) [not null]
  token varchar(255) [not null]
  expires timestamp [not null]

  indexes {
    (identifier, token) [pk]
  }
}

ref: attachments.secret_id > secrets.id

ref: friendship.user_id - user.id

ref: friendship.friend_id > user.id

ref: secrets.created_by_user_id > user.id

ref: users_to_secrets.userId > user.id

ref: users_to_secrets.secretId > secrets.id